# Generated by Django 3.1.1 on 2020-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brandname',
            field=models.CharField(max_length=50),
        ),
    ]
