# Generated by Django 3.1.1 on 2020-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200924_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variety',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
